version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-full:latest
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8085}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES-}
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - PORT_WEB_UI=${PORT_WEB_UI-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      
  terraform:
    image: hashicorp/terraform:1.3.3
    depends_on:
      - localstack
    volumes:
      - ./infra/terraform/:/infra
    working_dir: /infra
    entrypoint: >
     sh -c "
     terraform init 
     && terraform fmt 
     && terraform validate 
     && terraform plan -out='infra.out' 
     && terraform apply infra.out"