version: '3.8'

services:
  terraform:
    image: hashicorp/terraform:1.3.3
    volumes:
      - ./infra/terraform/:/infra
    working_dir: /infra
    entrypoint: sh -c "terraform init && terraform fmt && terraform plan -out='infra.out' && terraform apply infra.out"